import {
    AppWindow,
    Binary,
    FileJson,
    Hash,
    Link,
    Calculator,
    Regex,
    Shield,
    Mail,
    Network,
    Key,
    Search,
    Globe,
    FileDigit,
    Divide,
    FileDiff,
    QrCode,
    Palette,
    Fingerprint,
    FileType,
    Code,
    MonitorSmartphone,
} from "lucide-react"
import { Tool } from "@/types/tool.types"

export const TOOLS: Tool[] = [
    {
        id: "base64",
        name: "Base64 Converter",
        description: "Encode and decode Base64 data with URL safety options.",
        path: "/tools/base64",
        icon: Binary,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["data-transformation", "privacy-local-processing"],
        category: "application",
        status: "ready",
        keywords: ["base64", "encode", "decode", "url"]
    },
    {
        id: "hash",
        name: "Hash Generator",
        description: "Generate MD5, SHA1, SHA256, and SHA512 hashes.",
        path: "/tools/hash",
        icon: Hash,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["artifact-fingerprinting", "integrity-check"],
        category: "security",
        status: "ready",
        keywords: ["md5", "sha1", "sha256", "hash", "crypto"]
    },
    {
        id: "json",
        name: "JSON Formatter",
        description: "Validate, format, and minify JSON data.",
        path: "/tools/json",
        icon: FileJson,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "low",
        evidenceTags: ["data-transformation", "privacy-local-processing"],
        category: "application",
        status: "ready",
        keywords: ["json", "format", "minify", "validate"]
    },
    {
        id: "url",
        name: "URL Encoder",
        description: "Encode and decode URLs and URI components.",
        path: "/tools/url",
        icon: Link,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "low",
        evidenceTags: ["data-transformation", "privacy-local-processing"],
        category: "application",
        status: "ready",
        keywords: ["url", "encode", "decode", "uri"]
    },
    {
        id: "url-defang",
        name: "URL Defang/Refang",
        description: "Defang/refang URLs and canonicalize links for IOC workflows.",
        path: "/tools/url-defang",
        icon: Link,
        domainId: "network",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["ioc-safety", "triage-speed"],
        category: "security",
        status: "new",
        keywords: ["url", "defang", "refang", "canonicalize"]
    },
    {
        id: "timestamp",
        name: "Unix Timestamp",
        description: "Convert between Unix timestamps and human dates.",
        path: "/tools/timestamp",
        icon: Calculator,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "low",
        evidenceTags: ["timeline-analysis", "data-transformation"],
        category: "application",
        status: "ready",
        keywords: ["time", "unix", "date", "convert"]
    },
    {
        id: "regex",
        name: "Regex Tester",
        description: "Test regular expressions against text.",
        path: "/tools/regex",
        icon: Regex,
        domainId: "application",
        processingMode: "local",
        sensitivity: "low",
        evidenceTags: ["input-validation", "developer-productivity"],
        category: "application",
        status: "ready",
        keywords: ["regex", "test", "match"]
    },
    {
        id: "jwt",
        name: "JWT Decoder",
        description: "Decode and inspect JSON Web Tokens.",
        path: "/tools/jwt",
        icon: Key,
        domainId: "application",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["identity-security", "token-analysis"],
        category: "security",
        status: "ready",
        keywords: ["jwt", "token", "decode"]
    },
    {
        id: "jwt-verify",
        name: "JWT/JWS Verifier",
        description: "Verify JWT/JWS signatures and optional claims policy with secret, PEM, JWK, or JWKS URL.",
        path: "/tools/jwt-verify",
        icon: Key,
        domainId: "application",
        processingMode: "hybrid",
        sensitivity: "high",
        evidenceTags: ["identity-security", "token-validation", "api-authz"],
        category: "security",
        status: "new",
        keywords: ["jwt", "jws", "verify", "jwks"]
    },
    {
        id: "email",
        name: "Email Header Analyzer",
        description: "Parse and analyze email headers.",
        path: "/tools/email",
        icon: Mail,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["phishing-defense", "triage-speed", "soc-throughput"],
        category: "security",
        status: "ready",
        keywords: ["email", "header", "smtp"]
    },
    {
        id: "ioc",
        name: "IOC Extractor",
        description: "Extract URLs, domains, IPs, hashes, and CVEs from raw text.",
        path: "/tools/ioc",
        icon: Search,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["soc-throughput", "triage-speed"],
        category: "security",
        status: "new",
        keywords: ["ioc", "indicators", "threat", "triage"]
    },
    {
        id: "ioc-correlator",
        name: "IOC Correlator",
        description: "Compare two IOC datasets and identify overlap and unique indicators.",
        path: "/tools/ioc-correlator",
        icon: FileDiff,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["soc-throughput", "intel-correlation"],
        category: "security",
        status: "new",
        keywords: ["ioc", "correlate", "overlap", "threat-intel"]
    },
    {
        id: "ioc-normalizer",
        name: "IOC Canonicalizer",
        description: "Normalize defanged indicators, unicode/punycode domains, and deduplicate by canonical value.",
        path: "/tools/ioc-normalizer",
        icon: Link,
        domainId: "threat-intel",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["intel-fidelity", "ioc-hygiene"],
        category: "security",
        status: "new",
        keywords: ["ioc", "canonicalize", "defang", "punycode"]
    },
    {
        id: "user-agent",
        name: "User-Agent Analyzer",
        description: "Parse User-Agent strings into browser, OS, device, and automation signals.",
        path: "/tools/user-agent",
        icon: MonitorSmartphone,
        domainId: "network",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["session-analysis", "bot-detection"],
        category: "security",
        status: "new",
        keywords: ["user-agent", "ua", "browser", "fingerprint"]
    },
    {
        id: "subnet",
        name: "Subnet Calculator",
        description: "Calculate CIDR ranges and netmasks.",
        path: "/tools/subnet",
        icon: Network,
        domainId: "network",
        processingMode: "local",
        sensitivity: "low",
        evidenceTags: ["network-planning", "exposure-hygiene"],
        category: "network",
        status: "ready",
        keywords: ["cidr", "subnet", "network", "ip"]
    },
    {
        id: "password",
        name: "Password Generator",
        description: "Generate secure random passwords.",
        path: "/tools/password",
        icon: Shield,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["credential-hygiene", "identity-security"],
        category: "security",
        status: "ready",
        keywords: ["password", "secure", "generator"]
    },
    {
        id: "whois",
        name: "Whois Lookup",
        description: "Lookup domain registration details via RDAP (network request).",
        path: "/tools/whois",
        icon: Search,
        domainId: "network",
        processingMode: "network",
        sensitivity: "medium",
        evidenceTags: ["external-exposure", "threat-intel-context"],
        category: "network",
        status: "beta",
        keywords: ["whois", "domain", "lookup"]
    },
    {
        id: "dns-toolkit",
        name: "DNS Toolkit",
        description: "Query DNS-over-HTTPS records and inspect SPF/DMARC posture.",
        path: "/tools/dns",
        icon: Network,
        domainId: "network",
        processingMode: "network",
        sensitivity: "medium",
        evidenceTags: ["external-exposure", "email-authentication"],
        category: "network",
        status: "new",
        keywords: ["dns", "spf", "dmarc", "mx", "txt"]
    },
    {
        id: "certificate",
        name: "Certificate Decoder",
        description: "Inspect certificate text and derive PEM SHA-256 fingerprints.",
        path: "/tools/certificate",
        icon: FileDigit,
        domainId: "network",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["tls-hardening", "integrity-check"],
        category: "security",
        status: "beta",
        keywords: ["ssl", "cert", "pem", "decode"]
    },
    {
        id: "iplookup",
        name: "IP Lookup",
        description: "Classify IP addresses and optionally enrich with RDAP (network request).",
        path: "/tools/ip",
        icon: Globe,
        domainId: "network",
        processingMode: "network",
        sensitivity: "medium",
        evidenceTags: ["external-exposure", "threat-intel-context"],
        category: "network",
        status: "beta",
        keywords: ["ip", "geolocation", "lookup"]
    },
    {
        id: "port",
        name: "Port Checker",
        description: "Assess common ports and probe HTTP(S)-compatible endpoints from browser.",
        path: "/tools/port",
        icon: Divide,
        domainId: "network",
        processingMode: "network",
        sensitivity: "medium",
        evidenceTags: ["external-exposure", "attack-surface"],
        category: "network",
        status: "beta",
        keywords: ["port", "check", "open"]
    },
    {
        id: "diff",
        name: "Text Diff",
        description: "Compare two texts and find differences.",
        path: "/tools/diff",
        icon: FileDiff,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "low",
        evidenceTags: ["change-review", "triage-speed"],
        category: "application",
        status: "ready",
        keywords: ["diff", "compare", "text"]
    },
    {
        id: "http-headers",
        name: "HTTP Header Analyzer",
        description: "Score HTTP security headers and identify hardening gaps.",
        path: "/tools/http-headers",
        icon: Shield,
        domainId: "application",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["web-hardening", "api-authz"],
        category: "security",
        status: "new",
        keywords: ["http", "headers", "csp", "hsts"]
    },
    {
        id: "reputation",
        name: "Reputation Enricher",
        description: "Bulk-enrich domains/IPs with local scoring, RDAP, and optional provider proxy intel.",
        path: "/tools/reputation",
        icon: Search,
        domainId: "soc",
        processingMode: "hybrid",
        sensitivity: "high",
        evidenceTags: ["soc-throughput", "false-positive-reduction", "threat-intel-context"],
        category: "security",
        status: "new",
        keywords: ["reputation", "bulk", "abuseipdb", "virustotal"]
    },
    {
        id: "cve-prioritizer",
        name: "KEV/CVE Prioritizer",
        description: "Prioritize CVEs client-side using KEV, NVD feeds, CVSS, EPSS, exploit signals, and asset criticality.",
        path: "/tools/cve-prioritizer",
        icon: Search,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["kev-prioritization", "vulnerability-exploitation"],
        category: "security",
        status: "new",
        keywords: ["cve", "kev", "epss", "prioritization"]
    },
    {
        id: "secrets-scanner",
        name: "Secrets Scanner",
        description: "Detect leaked credentials and high-entropy tokens in pasted content.",
        path: "/tools/secrets-scanner",
        icon: Shield,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["secrets-sprawl", "credential-abuse"],
        category: "security",
        status: "new",
        keywords: ["secrets", "token", "credential", "leak"]
    },
    {
        id: "stix-taxii",
        name: "STIX/TAXII Utility",
        description: "Parse, validate, compare, and export STIX 2.1 bundles locally.",
        path: "/tools/stix-taxii",
        icon: FileJson,
        domainId: "threat-intel",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["intel-fidelity", "stix-misp-interoperability"],
        category: "security",
        status: "new",
        keywords: ["stix", "taxii", "threat-intel", "bundle"]
    },
    {
        id: "domain-spoof",
        name: "Domain Spoof Detector",
        description: "Score suspected spoofed domains using homoglyph, brand abuse, and domain-age signals.",
        path: "/tools/domain-spoof",
        icon: Globe,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["phishing-defense", "identity-abuse"],
        category: "security",
        status: "new",
        keywords: ["domain", "spoof", "homoglyph", "typosquat"]
    },
    {
        id: "sigma-helper",
        name: "Sigma Linter Helper",
        description: "Lint Sigma rules and generate backend query helpers with ATT&CK coverage checks.",
        path: "/tools/sigma-helper",
        icon: FileType,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["detection-quality", "rule-testing"],
        category: "security",
        status: "new",
        keywords: ["sigma", "siem", "attack", "detection"]
    },
    {
        id: "yara-local",
        name: "YARA Local Matcher",
        description: "Run local YARA-style matching against text or local files without upload.",
        path: "/tools/yara-local",
        icon: Search,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["malware-triage", "soc-throughput"],
        category: "security",
        status: "new",
        keywords: ["yara", "malware", "pattern", "scan"]
    },
    {
        id: "sbom-diff",
        name: "SBOM Diff & Triage",
        description: "Compare CycloneDX/SPDX BOMs and prioritize risky component changes.",
        path: "/tools/sbom-diff",
        icon: FileDiff,
        domainId: "supply-chain",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["supply-chain-risk", "vulnerability-exploitation"],
        category: "security",
        status: "new",
        keywords: ["sbom", "cyclonedx", "spdx", "supply-chain"]
    },
    {
        id: "security-header-builder",
        name: "Security Header Builder",
        description: "Generate CSP and security header presets with explicit compatibility tradeoffs.",
        path: "/tools/security-header-builder",
        icon: Shield,
        domainId: "application",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["web-hardening", "cors-misconfig"],
        category: "security",
        status: "new",
        keywords: ["csp", "headers", "hsts", "policy"]
    },
    {
        id: "qrcode",
        name: "QR Code Generator",
        description: "Generate QR codes from text.",
        path: "/tools/qrcode",
        icon: QrCode,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "low",
        evidenceTags: ["data-transformation", "offline-workflow"],
        category: "others",
        status: "ready",
        keywords: ["qr", "code", "generate"]
    },
    {
        id: "color",
        name: "Color Converter",
        description: "Convert HEX, RGB, and HSL colors.",
        path: "/tools/color",
        icon: Palette,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "low",
        evidenceTags: ["developer-productivity", "data-transformation"],
        category: "application",
        status: "ready",
        keywords: ["color", "hex", "rgb", "hsl"]
    },
    {
        id: "uuid",
        name: "UUID Generator",
        description: "Generate UUID v4 identifiers.",
        path: "/tools/uuid",
        icon: Fingerprint,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "low",
        evidenceTags: ["identifier-generation", "developer-productivity"],
        category: "application",
        status: "ready",
        keywords: ["uuid", "guid", "generate"]
    },
    {
        id: "markdown",
        name: "Markdown Preview",
        description: "Preview Markdown text.",
        path: "/tools/markdown",
        icon: FileType,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "low",
        evidenceTags: ["documentation-workflow", "developer-productivity"],
        category: "application",
        status: "ready",
        keywords: ["markdown", "preview", "md"]
    },
    {
        id: "html",
        name: "HTML Encoder",
        description: "Encode and decode HTML entities.",
        path: "/tools/html",
        icon: Code,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "low",
        evidenceTags: ["data-transformation", "xss-safety"],
        category: "application",
        status: "ready",
        keywords: ["html", "encode", "entity"]
    },

    // Phase 1 Domain Expansion Tools (SOC-first)
    {
        id: "alert-dedupe",
        name: "Alert Deduplication Simulator",
        description: "Cluster noisy alerts into deterministic buckets to estimate SOC false-positive reduction.",
        path: "/tools/alert-dedupe",
        icon: Shield,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["false-positive-reduction", "soc-throughput"],
        category: "security",
        status: "new",
        keywords: ["alert", "dedupe", "soc", "triage"]
    },
    {
        id: "detection-unit-test",
        name: "Detection Rule Unit Test Harness",
        description: "Run Sigma-like rule fixtures against expected detections to validate detection quality.",
        path: "/tools/detection-unit-test",
        icon: FileType,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["detection-quality", "rule-testing"],
        category: "security",
        status: "new",
        keywords: ["sigma", "unit test", "detection", "fixtures"]
    },
    {
        id: "attack-coverage",
        name: "ATT&CK Coverage Heatmap",
        description: "Summarize ATT&CK tactic and technique coverage from rule metadata.",
        path: "/tools/attack-coverage",
        icon: Search,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["attack-coverage", "detection-quality"],
        category: "security",
        status: "new",
        keywords: ["attack", "heatmap", "coverage", "rules"]
    },
    {
        id: "event-timeline",
        name: "Event Timeline Composer",
        description: "Compose and normalize incident event timelines for triage and post-incident review.",
        path: "/tools/event-timeline",
        icon: Calculator,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["triage-speed", "incident-response"],
        category: "security",
        status: "new",
        keywords: ["timeline", "incident", "triage", "events"]
    },
    {
        id: "log-schema-mapper",
        name: "Log Schema Mapper",
        description: "Map raw log fields to ECS/OCSF hints for faster normalization and ingestion planning.",
        path: "/tools/log-schema-mapper",
        icon: FileJson,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["schema-normalization", "soc-throughput"],
        category: "security",
        status: "new",
        keywords: ["ecs", "ocsf", "schema", "logs"]
    },
    {
        id: "ioc-confidence-ttl",
        name: "IOC Confidence + TTL Scorer",
        description: "Score indicator confidence and suggest TTL decay windows for operational feeds.",
        path: "/tools/ioc-confidence-ttl",
        icon: Search,
        domainId: "threat-intel",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["intel-fidelity", "ioc-freshness"],
        category: "security",
        status: "new",
        keywords: ["ioc", "confidence", "ttl", "intel"]
    },
    {
        id: "misp-stix-mapper",
        name: "MISP/STIX Mapper",
        description: "Transform simplified MISP exports into STIX bundles and run consistency checks.",
        path: "/tools/misp-stix-mapper",
        icon: FileJson,
        domainId: "threat-intel",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["stix-misp-interoperability", "intel-fidelity"],
        category: "security",
        status: "new",
        keywords: ["misp", "stix", "mapping", "consistency"]
    },
    {
        id: "artifact-integrity",
        name: "Artifact Integrity Packager",
        description: "Build chain-of-custody manifests with hash attestations for forensic artifacts.",
        path: "/tools/artifact-integrity",
        icon: FileDigit,
        domainId: "threat-intel",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["chain-of-custody", "dfir"],
        category: "security",
        status: "new",
        keywords: ["forensics", "integrity", "manifest", "custody"]
    },
    {
        id: "exposure-normalizer",
        name: "External Exposure Normalizer",
        description: "Normalize Nmap/Masscan/Shodan imports into a comparable exposure inventory.",
        path: "/tools/exposure-normalizer",
        icon: Network,
        domainId: "network",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["external-exposure", "asset-visibility"],
        category: "network",
        status: "new",
        keywords: ["nmap", "masscan", "shodan", "exposure"]
    },
    {
        id: "firewall-acl-analyzer",
        name: "Firewall/ACL Conflict Analyzer",
        description: "Detect duplicate, shadowed, and overly permissive firewall or ACL rules.",
        path: "/tools/firewall-acl-analyzer",
        icon: Shield,
        domainId: "network",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["acl-conflict", "network-hardening"],
        category: "network",
        status: "new",
        keywords: ["firewall", "acl", "conflict", "shadowing"]
    },
    {
        id: "tls-risk-explainer",
        name: "TLS Risk Explainer",
        description: "Explain TLS protocol/cipher/certificate risks from pasted scanner output.",
        path: "/tools/tls-risk-explainer",
        icon: Globe,
        domainId: "network",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["tls-hardening", "external-exposure"],
        category: "network",
        status: "new",
        keywords: ["tls", "ssl", "cipher", "hardening"]
    },
    {
        id: "openapi-authz-gap",
        name: "OpenAPI AuthZ Gap Analyzer",
        description: "Find missing or weak authorization requirements in OpenAPI documents.",
        path: "/tools/openapi-authz-gap",
        icon: AppWindow,
        domainId: "application",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["api-authz", "detection-quality"],
        category: "security",
        status: "new",
        keywords: ["openapi", "authz", "api", "security"]
    },
    {
        id: "cors-policy-analyzer",
        name: "CORS Policy Analyzer",
        description: "Assess CORS response policies and explain cross-origin abuse risk.",
        path: "/tools/cors-policy-analyzer",
        icon: Shield,
        domainId: "application",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["cors-misconfig", "api-authz"],
        category: "security",
        status: "new",
        keywords: ["cors", "origin", "headers", "browser"]
    },
    {
        id: "oauth-oidc-linter",
        name: "OAuth/OIDC Scope Minimizer",
        description: "Lint scope and token policy inputs to reduce excess identity permissions.",
        path: "/tools/oauth-oidc-linter",
        icon: Key,
        domainId: "cloud-iam",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["identity-governance", "least-privilege"],
        category: "security",
        status: "new",
        keywords: ["oauth", "oidc", "scopes", "token policy"]
    },
    {
        id: "iam-policy-analyzer",
        name: "IAM Policy Analyzer",
        description: "Lint AWS/Azure/GCP-style policies for wildcard privilege and risky grants.",
        path: "/tools/iam-policy-analyzer",
        icon: Key,
        domainId: "cloud-iam",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["identity-governance", "least-privilege"],
        category: "security",
        status: "new",
        keywords: ["iam", "aws", "azure", "gcp", "policy"]
    },
    {
        id: "lockfile-risk-diff",
        name: "Lockfile Risk Diff",
        description: "Diff lockfiles and flag dependency-confusion and naming-risk heuristics.",
        path: "/tools/lockfile-risk-diff",
        icon: FileDiff,
        domainId: "supply-chain",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["supply-chain-risk", "dependency-confusion"],
        category: "security",
        status: "new",
        keywords: ["lockfile", "dependency", "supply chain", "confusion"]
    },

    // Phase 2 researched onboarding (planned)
    {
        id: "ai-prompt-injection-triage",
        name: "AI Prompt Injection Triage",
        description: "Assess prompt, tool-call, and retrieval payloads for injection and policy-bypass patterns.",
        path: "/tools/ai-prompt-injection-triage",
        icon: AppWindow,
        domainId: "application",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["ai-security-governance", "prompt-injection"],
        category: "security",
        status: "planned",
        keywords: ["ai", "llm", "prompt injection", "tool abuse"]
    },
    {
        id: "browser-session-triage",
        name: "Browser Session Triage",
        description: "Correlate browser telemetry and identity events to investigate session-token abuse patterns.",
        path: "/tools/browser-session-triage",
        icon: Search,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["identity-abuse", "soc-throughput"],
        category: "security",
        status: "planned",
        keywords: ["browser", "session", "token theft", "triage"]
    },
    {
        id: "identity-blast-radius-simulator",
        name: "Identity Blast Radius Simulator",
        description: "Estimate lateral movement and privilege spread from compromised identities.",
        path: "/tools/identity-blast-radius-simulator",
        icon: Key,
        domainId: "cloud-iam",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["identity-governance", "least-privilege"],
        category: "security",
        status: "planned",
        keywords: ["identity", "blast radius", "privilege", "lateral movement"]
    },
    {
        id: "saas-oauth-app-risk",
        name: "SaaS OAuth App Risk Assessor",
        description: "Score third-party SaaS OAuth grants for risky scopes, tenant exposure, and consent drift.",
        path: "/tools/saas-oauth-app-risk",
        icon: Key,
        domainId: "cloud-iam",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["identity-governance", "oauth-risk"],
        category: "security",
        status: "planned",
        keywords: ["saas", "oauth", "consent", "scope risk"]
    },
    {
        id: "kev-patch-sla-tracker",
        name: "KEV Patch SLA Tracker",
        description: "Track active KEV exposure against internal patch SLAs and escalation thresholds.",
        path: "/tools/kev-patch-sla-tracker",
        icon: Network,
        domainId: "network",
        processingMode: "hybrid",
        sensitivity: "high",
        evidenceTags: ["kev-prioritization", "external-exposure"],
        category: "security",
        status: "planned",
        keywords: ["kev", "patching", "sla", "exposure"]
    },
    {
        id: "data-minimization-checker",
        name: "Data Minimization Policy Checker",
        description: "Validate event fields against data minimization and retention policy constraints.",
        path: "/tools/data-minimization-checker",
        icon: FileJson,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["privacy-governance", "data-minimization"],
        category: "security",
        status: "planned",
        keywords: ["privacy", "retention", "pii", "data minimization"]
    },
    {
        id: "ai-connector-egress-audit",
        name: "AI Connector Egress Audit",
        description: "Review outbound connector payloads and destinations for policy and data-loss risk.",
        path: "/tools/ai-connector-egress-audit",
        icon: FileDiff,
        domainId: "data-privacy",
        processingMode: "hybrid",
        sensitivity: "high",
        evidenceTags: ["ai-security-governance", "data-exfiltration"],
        category: "security",
        status: "planned",
        keywords: ["ai connector", "egress", "dlp", "policy"]
    },
    {
        id: "model-supply-chain-audit",
        name: "Model Supply Chain Audit",
        description: "Assess AI model provenance, dependency lineage, and package integrity controls.",
        path: "/tools/model-supply-chain-audit",
        icon: FileDiff,
        domainId: "supply-chain",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["supply-chain-risk", "ai-model-governance"],
        category: "security",
        status: "planned",
        keywords: ["model", "ai", "supply chain", "provenance"]
    },
    {
        id: "soar-playbook-dry-runner",
        name: "SOAR Playbook Dry Runner",
        description: "Run incident playbook branches against sample alerts to validate escalation and containment logic before production rollout.",
        path: "/tools/soar-playbook-dry-runner",
        icon: Shield,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["soc-throughput", "incident-response", "automation"],
        category: "security",
        status: "planned",
        keywords: ["soar", "playbook", "incident response", "automation"]
    },
    {
        id: "xdr-detection-tuning-benchmark",
        name: "XDR Detection Tuning Benchmark",
        description: "Benchmark detection noise, precision, and suppression impact using representative endpoint and identity event samples.",
        path: "/tools/xdr-detection-tuning-benchmark",
        icon: Search,
        domainId: "soc",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["false-positive-reduction", "detection-quality", "soc-throughput"],
        category: "security",
        status: "planned",
        keywords: ["xdr", "detection tuning", "precision", "false positives"]
    },
    {
        id: "threat-feed-fusion-normalizer",
        name: "Threat Feed Fusion Normalizer",
        description: "Merge commercial and open intelligence feeds into a deduplicated confidence-weighted indicator dataset.",
        path: "/tools/threat-feed-fusion-normalizer",
        icon: FileJson,
        domainId: "threat-intel",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["intel-fidelity", "ioc-freshness", "intel-correlation"],
        category: "security",
        status: "planned",
        keywords: ["threat intel", "feed fusion", "ioc", "deduplication"]
    },
    {
        id: "campaign-graph-builder",
        name: "Campaign Graph Builder",
        description: "Build actor-campaign-infrastructure graphs from incidents to visualize cluster overlap and repeated tradecraft.",
        path: "/tools/campaign-graph-builder",
        icon: Search,
        domainId: "threat-intel",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["intel-correlation", "dfir", "campaign-tracking"],
        category: "security",
        status: "planned",
        keywords: ["campaign", "graph", "threat actor", "infrastructure"]
    },
    {
        id: "asm-change-diff-tracker",
        name: "Attack Surface Change Tracker",
        description: "Track newly exposed ports, services, and hostnames between scans to prioritize risky external drift.",
        path: "/tools/asm-change-diff-tracker",
        icon: Network,
        domainId: "network",
        processingMode: "hybrid",
        sensitivity: "high",
        evidenceTags: ["external-exposure", "asset-visibility", "attack-surface"],
        category: "network",
        status: "planned",
        keywords: ["attack surface", "asm", "drift", "exposure"]
    },
    {
        id: "waf-rule-risk-simulator",
        name: "WAF Rule Risk Simulator",
        description: "Simulate allow/deny outcomes for common payload families to identify blind spots and overbroad bypasses.",
        path: "/tools/waf-rule-risk-simulator",
        icon: Shield,
        domainId: "network",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["web-hardening", "network-hardening", "false-positive-reduction"],
        category: "security",
        status: "planned",
        keywords: ["waf", "rule testing", "bypass", "traffic simulation"]
    },
    {
        id: "sast-finding-deduplicator",
        name: "SAST Finding Deduplicator",
        description: "Normalize and deduplicate findings from multiple SAST engines to reduce triage duplication and priority conflicts.",
        path: "/tools/sast-finding-deduplicator",
        icon: AppWindow,
        domainId: "application",
        processingMode: "local",
        sensitivity: "medium",
        evidenceTags: ["false-positive-reduction", "appsec-triage", "developer-productivity"],
        category: "security",
        status: "planned",
        keywords: ["sast", "dedupe", "appsec", "finding normalization"]
    },
    {
        id: "api-abuse-pattern-lab",
        name: "API Abuse Pattern Lab",
        description: "Replay known API abuse scenarios against request/response samples to detect authz bypass and business logic weakness.",
        path: "/tools/api-abuse-pattern-lab",
        icon: AppWindow,
        domainId: "application",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["api-authz", "business-logic-abuse", "detection-quality"],
        category: "security",
        status: "planned",
        keywords: ["api abuse", "authz bypass", "business logic", "appsec"]
    },
    {
        id: "cloud-permission-drift-detector",
        name: "Cloud Permission Drift Detector",
        description: "Compare IAM snapshots across time to surface risky privilege expansion, wildcard growth, and stale exceptions.",
        path: "/tools/cloud-permission-drift-detector",
        icon: Key,
        domainId: "cloud-iam",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["least-privilege", "identity-governance", "drift-detection"],
        category: "security",
        status: "planned",
        keywords: ["iam drift", "privilege creep", "cloud iam", "policy change"]
    },
    {
        id: "saas-entitlement-reviewer",
        name: "SaaS Entitlement Reviewer",
        description: "Review SaaS admin and high-risk permissions for orphaned accounts, over-privileged roles, and separation-of-duty conflicts.",
        path: "/tools/saas-entitlement-reviewer",
        icon: Key,
        domainId: "cloud-iam",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["identity-governance", "least-privilege", "access-review"],
        category: "security",
        status: "planned",
        keywords: ["saas", "entitlements", "identity governance", "access review"]
    },
    {
        id: "container-image-policy-linter",
        name: "Container Image Policy Linter",
        description: "Lint container image metadata and package manifests against supply-chain policy guardrails.",
        path: "/tools/container-image-policy-linter",
        icon: FileDiff,
        domainId: "supply-chain",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["supply-chain-risk", "container-security", "policy-linting"],
        category: "security",
        status: "planned",
        keywords: ["container", "image policy", "supply chain", "lint"]
    },
    {
        id: "artifact-provenance-verifier",
        name: "Artifact Provenance Verifier",
        description: "Validate software artifact provenance attestations and signing metadata for tamper and origin anomalies.",
        path: "/tools/artifact-provenance-verifier",
        icon: FileDigit,
        domainId: "supply-chain",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["provenance-attestation", "supply-chain-risk", "integrity-check"],
        category: "security",
        status: "planned",
        keywords: ["artifact", "provenance", "attestation", "signing"]
    },
    {
        id: "dlp-rule-tester",
        name: "DLP Rule Tester",
        description: "Test data-loss-prevention patterns against realistic payload samples to tune precision and reduce analyst fatigue.",
        path: "/tools/dlp-rule-tester",
        icon: FileJson,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["data-exfiltration", "privacy-governance", "false-positive-reduction"],
        category: "security",
        status: "planned",
        keywords: ["dlp", "rule testing", "data loss prevention", "precision"]
    },
    {
        id: "retention-policy-conflict-finder",
        name: "Retention Policy Conflict Finder",
        description: "Detect retention-policy conflicts between legal, privacy, and security logging requirements.",
        path: "/tools/retention-policy-conflict-finder",
        icon: FileJson,
        domainId: "data-privacy",
        processingMode: "local",
        sensitivity: "high",
        evidenceTags: ["data-minimization", "privacy-governance", "compliance-hygiene"],
        category: "security",
        status: "planned",
        keywords: ["retention", "policy conflict", "privacy", "compliance"]
    }
]
